---
name: On-demand ğŸ§‘â€ğŸ”¬

on:
  schedule:
    - cron: '45 3 * * 0'
  push:
    branches:
      - initialize-revdepcheck-action
  workflow_dispatch:

jobs:
  revdepcheck:
    name: revdepcheck â†©ï¸
    uses: insightsengineering/r.pkg.template/.github/workflows/revdepcheck.yaml@initialize-revdepcheck-action
